baseURL = "http://websitewithtabs.netlify.com"
languageCode = "en-us"
title = "My New Hugo Site"

[ params ]
BackgroundImages = ["bg/1.jpg", "bg/2.jpg", "bg/3.jpg", "bg/4.jpg", "bg/5.jpg"]
BackgroundStyle = "#657383"

[[ params.nav ]]
name = "Python Basics"
section = "courses"
tag = "python"
icon = "code"

[[ params.nav ]]
name = "Data Science"
section = "courses"
tag = "data"
icon = "database"

[[ params.nav ]]
name = "AI"
section = "courses"
tag = "ai"
icon = "braille"

[[ params.nav ]]
name = "3D Printing"
section = "courses"
tag = "cad"
icon = "cube"

[[ params.nav ]]
name = "VR"
section = "courses"
tag = "vr"
icon = "eye"

[[ params.nav ]]
name = "AR"
section = "courses"
tag = "ar"
icon = "cubes"

[[ params.nav ]]
name = "Web Design"
section = "courses"
tag = "web"
icon = "laptop"

[[ params.nav ]]
name = "App Design"
section = "courses"
tag = "app"
icon = "mobile"

[[ params.nav ]]
name = "Embedded Systems"
section = "courses"
tag = "embedded"
icon = "microchip"

[[ params.nav ]]
name = "Home"
section = ""
tag = ""
icon = "home"

[[params.plugins.js]]
link = "plugins/slate/slate.js"

[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/tinycolor.js"
[[params.plugins.js]]
link = "plugins/shuffle.min.js"

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"